spring:
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html


## log 를 통해 출력
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

